services:

  # Frontend React app
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - bakeaura-network

  # Your Spring Boot app
  app:
    build: ./backend          # build using Dockerfile in current directory,create the image of the project
    ports:
      - "8080:8080"    # host_port:container_port
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bakeaura_db
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DELIVERY_MAX_RADIUS_KM=${DELIVERY_MAX_RADIUS_KM}
      - DELIVERY_AVERAGE_SPEED_KMPH=${DELIVERY_AVERAGE_SPEED_KMPH}
      - DELIVERY_ROAD_DISTANCE_FACTOR=${DELIVERY_ROAD_DISTANCE_FACTOR}
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}
      - APP_FRONTEND_URL=${APP_FRONTEND_URL:-http://localhost}
    depends_on:
      - postgres
      - redis
    networks:
      - bakeaura-network
    # Wait for postgres and redis to start before starting the app

  # PostgreSQL database
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=bakeaura_db
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Named volume: data persists even when container stops
    networks:
      - bakeaura-network

  # Redis cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # Alpine = smaller image size, same functionality
    networks:
      - bakeaura-network

volumes:
  postgres_data:
  # Docker manages this volume on your machine

networks:
  bakeaura-network:
    driver: bridge
